const data = {
    products: [
        {
            //_id: '1',
            name: 'Nike Slim shirt',
            slug: 'nike-slim-shirt',
            categoey: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality shirt',
        },
        {
            //_id: '2',
            name: 'Puma Slim shirt',
            slug: 'puma-slim-shirt',
            categoey: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality shirt',
        },
        {
            //_id: '3',
            name: 'Adidas Slim shirt',
            slug: 'adidas-slim-shirt',
            categoey: 'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 1,
            numReviews: 10,
            description: 'hight quality shirt',
        },
    ],
};

export default data;